ts_serie_heladeras <- ts(Heladeras_mensual, start = c(2018,3), frequency = 12)
ggAcf(ts_serie_heladeras)
plot(ts_serie_heladeras)
ggseasonplot(ts_serie_heladeras)

sehwa_serie_heladeras <- hw(ts_serie_heladeras, h = 12, seasonal = "additive", initial = "simple")
plot(sehwa_serie_heladeras)
lines(sehwa_serie_heladeras$fitted, col="red")
summary(sehwa_serie_heladeras)
sehwm_serie_heladeras <- hw(ts_serie_heladeras, h = 12, seasonal = "multiplicative", initial = "simple")
plot(sehwm_serie_heladeras)
lines(sehwm_serie_heladeras$fitted, col="red")
summary(sehwm_serie_heladeras)

checkresiduals(sehwm_serie_heladeras)
Box.test(sehwm_serie_heladeras$residuals, type = "Ljung-Box", lag = 20, fitdf = 17)
t.test(sehwm_serie_heladeras$residuals)
jarque.bera.test(sehwm_serie_heladeras$residuals)
qqnorm(sehwm_serie_heladeras$residuals)
qqline(sehwm_serie_heladeras$residuals)